version: '3.8'
services:
    postgres:
        image: postgres:14.1-alpine
        hostname: postgres
        restart: always
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DIALECT: ${POSTGRES_DIALECT}
            POSTGRES_DB: ${POSTGRES_DB}
            NODE_ENV: ${NODE_ENV}
        ports:
            - '5432:5432'
        volumes:
            - cryptomarketcap:/var/lib/postgresql/data
volumes:
    cryptomarketcap:
        driver: local
